// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAninPxbS02HML7gNDfdNYT56xPluoPzFg',
    appId: '1:550563013269:web:0422d55a254e009a0a719c',
    messagingSenderId: '550563013269',
    projectId: 'se-stock-app',
    authDomain: 'se-stock-app.firebaseapp.com',
    databaseURL: 'https://se-stock-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'se-stock-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwVlenSkyY3b4rL8-Nyt94TVLujNGj7rw',
    appId: '1:550563013269:android:e7652a47f8738c0c0a719c',
    messagingSenderId: '550563013269',
    projectId: 'se-stock-app',
    databaseURL: 'https://se-stock-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'se-stock-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq_pMtuEGYRn5aRmOljpYjxQR5P0nXy1I',
    appId: '1:550563013269:ios:14de184d26db6d970a719c',
    messagingSenderId: '550563013269',
    projectId: 'se-stock-app',
    databaseURL: 'https://se-stock-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'se-stock-app.firebasestorage.app',
    iosBundleId: 'com.example.seStockApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq_pMtuEGYRn5aRmOljpYjxQR5P0nXy1I',
    appId: '1:550563013269:ios:14de184d26db6d970a719c',
    messagingSenderId: '550563013269',
    projectId: 'se-stock-app',
    databaseURL: 'https://se-stock-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'se-stock-app.firebasestorage.app',
    iosBundleId: 'com.example.seStockApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAninPxbS02HML7gNDfdNYT56xPluoPzFg',
    appId: '1:550563013269:web:7c0cc4ba52bf64c70a719c',
    messagingSenderId: '550563013269',
    projectId: 'se-stock-app',
    authDomain: 'se-stock-app.firebaseapp.com',
    databaseURL: 'https://se-stock-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'se-stock-app.firebasestorage.app',
  );
}
